import type { Locale } from "./config";
import type { InfoCopy, InfoSectionCopy } from "./info-types";

const privacyEnglish: InfoSectionCopy[] = [
  { title: "1. The short version", paragraphs: ["AI Language Tutor is built around personal practice. We use information to provide conversations, corrections, translations, pronunciation practice, account access, and product support. We do not sell your personal information.", "The current website prototype may show demo flows without connecting to a production authentication provider. When production account, payment, or AI providers are connected, this policy will be updated to describe those services precisely."] },
  { title: "2. Information you provide", paragraphs: ["Depending on the features you use, this may include account details, selected languages and level, goals, tutor preferences, messages, saved phrases, corrections, voice input, and support messages."], bullets: ["Your name, email address, and sign-in provider.", "Your native language, target language, level, and learning goals.", "Messages, saved phrases, corrections, and learning notes.", "Voice input or audio recordings when you activate speaking features."] },
  { title: "3. Information collected automatically", paragraphs: ["We may receive basic technical information such as browser type, device category, approximate region, pages viewed, and error information. This helps us keep the product secure and improve the flows that need attention. We do not use conversation content to build an advertising profile."] },
  { title: "4. How we use information", bullets: ["Provide tutor conversations, translation, text-to-speech, and pronunciation practice.", "Remember settings, saved words, conversation history, and progress.", "Personalize prompts, corrections, examples, and practice suggestions.", "Communicate about account, service, security, and support matters.", "Monitor reliability, prevent abuse, and improve the product."] },
  { title: "5. AI and service providers", paragraphs: ["Some features may rely on providers for authentication, speech recognition, language generation, translation, hosting, analytics, or payments. We share the minimum information needed to perform the requested service and do not authorize providers to use private practice content for unrelated advertising."] },
  { title: "6. Voice and conversation data", paragraphs: ["Voice input is sent for transcription, conversation, or pronunciation feedback when you activate those features. We work to limit retention and access to what is needed to deliver the feature and keep history available when you choose to save it. Please do not share highly sensitive information in a practice conversation."] },
  { title: "7. Your choices", bullets: ["Choose text input, voice input, or neither.", "Review or remove saved words and conversation history where controls are available.", "Ask us to correct, export, or delete account information, subject to legal limits.", "Stop receiving non-essential product messages through the available unsubscribe option."] },
  { title: "8. Retention and security", paragraphs: ["We keep information for as long as reasonably needed to provide the service, maintain records, resolve disputes, meet legal obligations, or improve reliability. We use reasonable safeguards, but no internet service can guarantee absolute security."] },
  { title: "9. Children and international use", paragraphs: ["AI Language Tutor is not directed to children under 13. Our providers may process information in countries other than where you live, with steps appropriate to the service and applicable law."] },
  { title: "10. Contact and policy changes", paragraphs: ["For privacy questions or requests, email scottthornton815@gmail.com. We may update this policy when the product, providers, or legal requirements change. The date above shows when the current version was published."] }
];

const termsEnglish: InfoSectionCopy[] = [
  { title: "1. Using the service", paragraphs: ["AI Language Tutor provides conversational language-learning tools, including text and voice practice, translations, explanations, feedback, and related features. You may use the service only when you can legally enter this agreement and in accordance with these terms."] },
  { title: "2. Accounts and sign-in", paragraphs: ["Some features require an account. Keep your sign-in details secure and make sure the information connected to your account is accurate. You are responsible for activity through your account unless you promptly report unauthorized access."] },
  { title: "3. AI-generated learning content", paragraphs: ["Tutor responses are generated to support practice and may contain mistakes or culturally unsuitable phrasing. Treat them as learning suggestions rather than professional, legal, medical, or safety advice. You remain responsible for deciding what to say in real situations."] },
  { title: "4. Acceptable use", paragraphs: ["You may not use the service to:"], bullets: ["Break the law, infringe another person's rights, or facilitate harm.", "Harass, threaten, impersonate, exploit, or target another person.", "Upload malware, attempt unauthorized access, or interfere with service reliability.", "Probe, scrape, copy, reverse engineer, or reproduce the product except where law allows it.", "Submit private information about another person without permission.", "Evade usage limits, payment controls, security measures, or account restrictions."] },
  { title: "5. Plans, payments, and trials", paragraphs: ["Available plans, prices, limits, and features are shown on the Pricing page. A free experience may have limits. Paid plans may renew according to the option selected at checkout, where the price, billing interval, taxes, and fees will be shown."] },
  { title: "6. Cancellation and refunds", paragraphs: ["You may cancel a recurring plan using the account or payment controls made available for your purchase. Refund eligibility depends on the purchase channel, local law, and the terms shown at checkout. For billing help, contact scottthornton815@gmail.com."] },
  { title: "7. Your content and our rights", paragraphs: ["You keep the rights you already have in messages, examples, and recordings you submit. You give us the limited permission needed to host, process, transmit, and display that content to provide requested features. The product, interface, branding, software, and original materials belong to AI Language Tutor or its licensors."] },
  { title: "8. Availability and changes", paragraphs: ["We are building and improving the service continuously. Features may change, be paused, or be removed, and we do not promise that every feature will be available at every moment or on every device. Continued use after updated terms take effect means you accept them."] },
  { title: "9. Suspension and termination", paragraphs: ["We may limit or suspend access to protect users, the service, providers, or the public; investigate abuse; address unpaid charges; or comply with law. You may stop using the service at any time."] },
  { title: "10. Disclaimers and limits", paragraphs: ["To the extent permitted by law, the service is provided on an as-available basis without guarantees that it will be uninterrupted, error-free, or suitable for every learning goal. Nothing in these terms limits rights or remedies that cannot legally be limited in your location."] },
  { title: "11. Contact", paragraphs: ["Questions about these terms can be sent to scottthornton815@gmail.com. For general product help, use the Contact page."] }
];

type LocalizedInfo = {
  shell: InfoCopy["shell"];
  contact: InfoCopy["contact"];
  privacy: Omit<InfoCopy["privacy"], "sections"> & { sectionTitles: string[]; sectionTexts: string[] };
  terms: Omit<InfoCopy["terms"], "sections"> & { sectionTitles: string[]; sectionTexts: string[] };
};

function textSections(titles: string[], texts: string[]): InfoSectionCopy[] {
  return titles.map((title, index) => ({ title, paragraphs: [texts[index] ?? ""] }));
}

const english: InfoCopy = {
  locale: "en",
  shell: { back: "Back to AI Language Tutor", updatedLabel: "Last updated", footerBrand: "AI Language Tutor", policyNavigation: "Policy navigation", navigation: { contact: "Contact", privacy: "Privacy", terms: "Terms" } },
  contact: { eyebrow: "CONTACT", title: "Let's make speaking practice better.", lead: "Need help, have feedback, or want to work together? Send us a note and tell us what you are trying to learn.", updated: "August 24, 2026", chooseTitle: "Choose the right place to start", cards: [{ label: "Product support", title: "Something is not working?", body: "Tell us what happened, which language you were practicing, and what device or browser you were using.", email: "support@ailanguagetutor.online" }, { label: "Ideas and feedback", title: "Help shape the tutor", body: "Tell us which conversations you want to practice, which corrections feel useful, or where the experience gets in your way.", email: "hello@ailanguagetutor.online" }, { label: "Partnerships", title: "Build with us", body: "We are open to conversations with language teachers, learning communities, and teams exploring conversation-first practice.", email: "partners@ailanguagetutor.online" }], supportTitle: "What to include in a support message", supportLead: "A short, specific message helps us get to a useful answer sooner. Include:", supportBullets: ["The language you were learning and the practice mode you used.", "The page or action where the problem appeared.", "What you expected to happen and what happened instead.", "Your browser, device, and approximate time of the issue.", "A screenshot or short screen recording when the layout or audio is involved."], calloutTitle: "We read every message.", calloutBody: "Support is handled by email while the product is growing. We aim to reply within two business days, but complex audio or account issues may take a little longer to investigate.", privacyNote: "Questions about how we handle information? Read our", privacyLink: "Privacy Policy" },
  privacy: { eyebrow: "PRIVACY", title: "Your practice is personal.", lead: "This policy explains what information AI Language Tutor may handle, why we use it, and the choices you have.", updated: "August 24, 2026", sections: privacyEnglish },
  terms: { eyebrow: "TERMS", title: "A clear place to practice.", lead: "These terms explain the basics for using AI Language Tutor, including accounts, plans, content, and responsible use.", updated: "August 24, 2026", sections: termsEnglish }
};

const localized: Record<Exclude<Locale, "en">, LocalizedInfo> = {
  ja: {
    shell: { back: "AI Language Tutor に戻る", updatedLabel: "最終更新", footerBrand: "AI Language Tutor", policyNavigation: "ポリシー", navigation: { contact: "お問い合わせ", privacy: "プライバシー", terms: "利用規約" } },
    contact: { eyebrow: "お問い合わせ", title: "話す練習を、もっと良く。", lead: "使い方で困ったとき、改善のアイデアがあるとき、またはご一緒したいときは、学びたいことを添えてご連絡ください。", updated: "2026年8月24日", chooseTitle: "目的に合う窓口を選ぶ", cards: [{ label: "プロダクトサポート", title: "うまく動かないとき", body: "起きたこと、練習していた言語、使用した端末やブラウザを教えてください。状況を切り分けやすくなります。", email: "support@ailanguagetutor.online" }, { label: "アイデア・ご意見", title: "Tutorを一緒につくる", body: "練習したい会話や役立った訂正、使いにくかった場面を聞かせてください。", email: "hello@ailanguagetutor.online" }, { label: "パートナーシップ", title: "学びの場を広げる", body: "語学講師、学習コミュニティ、会話中心の学習に取り組むチームとの連携を歓迎します。", email: "partners@ailanguagetutor.online" }], supportTitle: "サポートに書いてほしいこと", supportLead: "短く具体的に書いていただくと、より早く適切にご案内できます。", supportBullets: ["学習中の言語と使用したモード", "問題が起きたページや操作", "期待していた結果と実際の結果", "ブラウザ、端末、発生したおおよその時刻", "画面や音声の問題ならスクリーンショットや短い録画"], calloutTitle: "すべてのメッセージを確認しています。", calloutBody: "現在のサポートはメールで対応しています。通常は2営業日以内の返信を目指しますが、音声やアカウントの調査にはもう少し時間がかかる場合があります。", privacyNote: "情報の取り扱いについては", privacyLink: "プライバシーポリシー" },
    privacy: { eyebrow: "プライバシー", title: "あなたの練習を大切に扱います。", lead: "AI Language Tutorが扱う情報、その利用目的、あなたが選べることを説明します。", updated: "2026年8月24日", sectionTitles: ["1. 要点", "2. ご提供いただく情報", "3. 自動的に収集される情報", "4. 情報の利用目的", "5. AIとサービス提供者", "6. 音声と会話データ", "7. あなたの選択", "8. 保存期間と安全対策", "9. お子さまと海外からの利用", "10. お問い合わせと変更"], sectionTexts: ["このサービスは個人の練習のために、会話、訂正、翻訳、発音練習、アカウント管理、サポートを提供します。個人情報を販売することはありません。", "氏名、メールアドレス、ログイン方法、母語・学習言語、レベル、目標、Tutorの設定、メッセージ、保存した表現、音声入力などが含まれます。", "ブラウザや端末の種類、閲覧したページ、おおよその地域、エラー情報など、サービスの安全性と改善に必要な技術情報を取得することがあります。", "依頼された会話や翻訳を提供し、設定・履歴・進捗を保存し、訂正や練習提案を個人に合わせ、サポートと安全対策を行うために使います。", "認証、音声認識、文章生成、翻訳、ホスティング、分析、決済の専門サービスを利用する場合があります。目的に必要な最小限の情報だけを共有します。", "音声は、あなたが機能を使ったときに文字起こし、会話、発音フィードバックのために処理されます。練習には機密情報を入力しないでください。", "テキスト入力と音声入力を選べます。利用できる範囲で保存語句や履歴を削除したり、アカウント情報の訂正・削除を依頼したりできます。", "サービス提供、記録管理、紛争対応、法令遵守に必要な期間だけ情報を保持します。合理的な安全対策を行いますが、インターネット上の安全を完全に保証することはできません。", "本サービスは13歳未満の子どもを対象としていません。提供者が居住国以外で情報を処理する場合は、適用法に応じた対策を講じます。", "プライバシーに関する質問は privacy@ailanguagetutor.online へ。サービスや法令の変更に応じて、このポリシーを更新することがあります。"] },
    terms: { eyebrow: "利用規約", title: "安心して練習できる場所に。", lead: "アカウント、プラン、投稿内容、責任ある利用について、AI Language Tutorの基本ルールを説明します。", updated: "2026年8月24日", sectionTitles: ["1. サービスの利用", "2. アカウントとログイン", "3. AIが生成する学習内容", "4. 禁止される利用", "5. プラン・決済・体験", "6. 解約と返金", "7. 投稿内容と権利", "8. 提供状況と変更", "9. 利用停止と終了", "10. 免責と制限", "11. お問い合わせ"], sectionTexts: ["テキスト・音声練習、翻訳、説明、フィードバックなどの語学学習機能を提供します。本規約と適用法に従って利用してください。", "アカウント情報を正確に保ち、ログイン情報を安全に管理してください。不正利用に気づいたら速やかにご連絡ください。", "Tutorの回答は練習用の提案であり、誤りや状況に合わない表現を含むことがあります。専門家の助言や安全上の判断の代わりにはなりません。", "違法行為、他者への嫌がらせ、不正アクセス、マルウェアの送信、無断転載、利用制限や安全対策の回避は禁止です。", "料金、更新条件、利用制限、機能はPricingページと決済画面に表示します。無料体験にも時間や機能の制限がある場合があります。", "定期プランは購入時に案内された方法で解約できます。返金は購入経路、地域の法令、決済時の条件によって決まります。", "送信した文章や録音について、あなたがもともと持つ権利は維持されます。機能提供に必要な範囲で処理・表示する許可をいただきます。", "機能は改善のため変更、一時停止、終了することがあります。常にすべての端末で利用できるとは限りません。", "安全確保、規約違反、未払い、法令対応が必要な場合、利用を制限または停止することがあります。", "法令で許される範囲で、サービスを現状有姿で提供します。AIの回答だけを根拠にした判断について保証はしません。", "規約については legal@ailanguagetutor.online へ。一般的なサポートはお問い合わせページをご利用ください。"] }
  },
  th: {
    shell: { back: "กลับไปที่ AI Language Tutor", updatedLabel: "อัปเดตล่าสุด", footerBrand: "AI Language Tutor", policyNavigation: "นโยบาย", navigation: { contact: "ติดต่อเรา", privacy: "ความเป็นส่วนตัว", terms: "ข้อกำหนด" } },
    contact: { eyebrow: "ติดต่อเรา", title: "ช่วยให้การฝึกพูดดีขึ้นไปด้วยกัน", lead: "ต้องการความช่วยเหลือ มีความคิดเห็น หรืออยากร่วมงานกับเราไหม เล่าให้เราฟังว่าคุณกำลังเรียนอะไรอยู่", updated: "24 สิงหาคม 2026", chooseTitle: "เลือกช่องทางที่ตรงกับเรื่องของคุณ", cards: [{ label: "ช่วยเหลือการใช้งาน", title: "มีบางอย่างทำงานไม่ถูกต้องใช่ไหม", body: "บอกสิ่งที่เกิดขึ้น ภาษาที่กำลังฝึก อุปกรณ์ และเบราว์เซอร์ที่ใช้ รายละเอียดเหล่านี้ช่วยให้เราตรวจสอบได้เร็วขึ้น", email: "support@ailanguagetutor.online" }, { label: "ไอเดียและคำแนะนำ", title: "ช่วยพัฒนา Tutor ไปด้วยกัน", body: "บอกบทสนทนาที่อยากฝึก การแก้ไขที่เป็นประโยชน์ หรือจุดที่ทำให้การใช้งานสะดุด", email: "hello@ailanguagetutor.online" }, { label: "ความร่วมมือ", title: "สร้างโอกาสการเรียนรู้ร่วมกัน", body: "เรายินดีพูดคุยกับครูภาษา ชุมชนผู้เรียน และทีมที่สนใจการฝึกภาษาผ่านบทสนทนา", email: "partners@ailanguagetutor.online" }], supportTitle: "ข้อมูลที่ควรใส่ในข้อความขอความช่วยเหลือ", supportLead: "ข้อความสั้นและเจาะจงจะช่วยให้เราแนะนำวิธีแก้ได้เร็วขึ้น ควรระบุ:", supportBullets: ["ภาษาที่เรียนและโหมดที่ใช้", "หน้าหรือขั้นตอนที่พบปัญหา", "สิ่งที่คาดว่าจะเกิดขึ้นและสิ่งที่เกิดขึ้นจริง", "เบราว์เซอร์ อุปกรณ์ และเวลาคร่าว ๆ", "ภาพหน้าจอหรือวิดีโอสั้น ๆ หากเกี่ยวกับหน้าจอหรือเสียง"], calloutTitle: "เราอ่านทุกข้อความ", calloutBody: "ขณะนี้ทีมงานดูแลผ่านอีเมล เราตั้งใจตอบกลับภายใน 2 วันทำการ แต่อาจใช้เวลานานขึ้นหากต้องตรวจสอบเสียงหรือบัญชีอย่างละเอียด", privacyNote: "ดูรายละเอียดการจัดการข้อมูลได้ใน", privacyLink: "นโยบายความเป็นส่วนตัว" },
    privacy: { eyebrow: "ความเป็นส่วนตัว", title: "ข้อมูลการฝึกของคุณเป็นเรื่องส่วนตัว", lead: "นโยบายนี้อธิบายข้อมูลที่ AI Language Tutor อาจจัดการ เหตุผลที่ใช้ และทางเลือกของคุณ", updated: "24 สิงหาคม 2026", sectionTitles: ["1. สรุปสั้น ๆ", "2. ข้อมูลที่คุณให้เรา", "3. ข้อมูลที่เก็บโดยอัตโนมัติ", "4. เราใช้ข้อมูลอย่างไร", "5. AI และผู้ให้บริการ", "6. ข้อมูลเสียงและบทสนทนา", "7. ทางเลือกของคุณ", "8. การเก็บรักษาและความปลอดภัย", "9. เด็กและการใช้งานข้ามประเทศ", "10. ติดต่อและการเปลี่ยนแปลง"], sectionTexts: ["เราใช้ข้อมูลเพื่อให้บริการบทสนทนา การแก้ไข การแปล การฝึกออกเสียง การเข้าสู่ระบบ และการช่วยเหลือ เราไม่ขายข้อมูลส่วนบุคคลของคุณ", "อาจรวมถึงชื่อ อีเมล วิธีเข้าสู่ระบบ ภาษาแม่ ภาษาที่เรียน ระดับ เป้าหมาย การตั้งค่า ข้อความ วลีที่บันทึก และเสียงที่คุณส่งเมื่อเปิดใช้ฟีเจอร์เสียง", "เราอาจได้รับข้อมูลทางเทคนิค เช่น เบราว์เซอร์ ประเภทอุปกรณ์ ภูมิภาคโดยประมาณ หน้าที่เข้าชม และข้อมูลข้อผิดพลาด เพื่อดูแลความปลอดภัยและปรับปรุงผลิตภัณฑ์", "ใช้เพื่อให้บริการที่คุณร้องขอ จำการตั้งค่าและประวัติ ปรับคำแนะนำให้เหมาะกับคุณ สื่อสารเรื่องบัญชี และป้องกันการใช้งานที่ไม่เหมาะสม", "เราอาจใช้ผู้ให้บริการด้านการยืนยันตัวตน การรู้จำเสียง การสร้างภาษา การแปล โฮสติ้ง การวิเคราะห์ และการชำระเงิน โดยแบ่งปันข้อมูลเท่าที่จำเป็น", "เสียงจะถูกส่งไปประมวลผลเมื่อคุณเปิดใช้การถอดเสียง การสนทนา หรือคำแนะนำการออกเสียง โปรดอย่าใส่ข้อมูลลับในการฝึก", "คุณเลือกใช้ข้อความหรือเสียงได้ และขอลบหรือแก้ไขข้อมูลบัญชีได้ภายใต้ข้อจำกัดทางกฎหมายและการดำเนินงาน", "เราจะเก็บข้อมูลเท่าที่จำเป็นต่อการให้บริการ การทำตามกฎหมาย และการแก้ปัญหา พร้อมใช้มาตรการป้องกันตามสมควร", "บริการนี้ไม่ได้ออกแบบมาสำหรับเด็กอายุต่ำกว่า 13 ปี ผู้ให้บริการอาจประมวลผลข้อมูลในประเทศอื่นตามกฎหมายที่เกี่ยวข้อง", "ติดต่อเรื่องความเป็นส่วนตัวได้ที่ privacy@ailanguagetutor.online เราอาจปรับปรุงนโยบายเมื่อผลิตภัณฑ์ ผู้ให้บริการ หรือกฎหมายเปลี่ยนแปลง"] },
    terms: { eyebrow: "ข้อกำหนด", title: "พื้นที่สำหรับฝึกภาษาอย่างชัดเจน", lead: "ข้อกำหนดนี้อธิบายหลักการใช้ AI Language Tutor บัญชี แผนบริการ เนื้อหา และการใช้งานอย่างรับผิดชอบ", updated: "24 สิงหาคม 2026", sectionTitles: ["1. การใช้บริการ", "2. บัญชีและการเข้าสู่ระบบ", "3. เนื้อหาการเรียนรู้จาก AI", "4. การใช้งานที่ไม่อนุญาต", "5. แผน การชำระเงิน และช่วงทดลอง", "6. การยกเลิกและการคืนเงิน", "7. เนื้อหาของคุณและสิทธิของเรา", "8. ความพร้อมให้บริการและการเปลี่ยนแปลง", "9. การระงับและการยุติ", "10. ข้อจำกัดความรับผิด", "11. ติดต่อเรา"], sectionTexts: ["บริการประกอบด้วยการฝึกภาษาแบบข้อความและเสียง การแปล คำอธิบาย และคำแนะนำ คุณต้องใช้บริการตามข้อกำหนดและกฎหมายที่ใช้บังคับ", "รักษาข้อมูลบัญชีให้ถูกต้องและเก็บข้อมูลเข้าสู่ระบบให้ปลอดภัย หากพบการเข้าถึงโดยไม่ได้รับอนุญาต โปรดแจ้งเราโดยเร็ว", "คำตอบของ Tutor มีไว้เพื่อการฝึกและอาจมีข้อผิดพลาดหรือไม่เหมาะกับบริบท จึงไม่ใช่คำแนะนำทางวิชาชีพ กฎหมาย การแพทย์ หรือความปลอดภัย", "ห้ามใช้บริการเพื่อทำผิดกฎหมาย คุกคามผู้อื่น เข้าถึงระบบโดยไม่ได้รับอนุญาต ส่งมัลแวร์ คัดลอกบริการ หรือหลบเลี่ยงข้อจำกัด", "ราคา รอบการเรียกเก็บเงิน ข้อจำกัด และฟีเจอร์จะแสดงในหน้าราคาและหน้าชำระเงิน แผนฟรีอาจมีข้อจำกัดด้านเวลาและการใช้งาน", "ยกเลิกแผนต่ออายุได้ผ่านช่องทางที่แสดงตอนซื้อ สิทธิ์คืนเงินขึ้นอยู่กับช่องทางซื้อ กฎหมายท้องถิ่น และเงื่อนไขตอนชำระเงิน", "คุณยังคงมีสิทธิ์ในเนื้อหาที่คุณสร้าง และอนุญาตให้เราประมวลผลเท่าที่จำเป็นต่อการให้บริการ ส่วนซอฟต์แวร์และแบรนด์เป็นของเราหรือผู้อนุญาต", "ฟีเจอร์อาจเปลี่ยน หยุดชั่วคราว หรือยุติได้ตามการพัฒนาผลิตภัณฑ์ เราไม่รับประกันว่าทุกฟีเจอร์จะพร้อมใช้งานตลอดเวลา", "เราอาจจำกัดหรือระงับการใช้งานเพื่อความปลอดภัย การละเมิดข้อกำหนด การค้างชำระ หรือการปฏิบัติตามกฎหมาย", "บริการให้ตามสภาพเท่าที่มีภายใต้ขอบเขตที่กฎหมายอนุญาต และไม่รับประกันความถูกต้องหรือความเหมาะสมของคำตอบ AI ทุกกรณี", "ส่งคำถามเกี่ยวกับข้อกำหนดไปที่ legal@ailanguagetutor.online ส่วนความช่วยเหลือทั่วไปให้ใช้หน้าติดต่อเรา"] }
  },
  "zh-CN": {
    shell: { back: "返回 AI Language Tutor", updatedLabel: "最后更新", footerBrand: "AI Language Tutor", policyNavigation: "政策导航", navigation: { contact: "联系我们", privacy: "隐私政策", terms: "服务条款" } },
    contact: { eyebrow: "联系我们", title: "一起把口语练习做得更好", lead: "遇到问题、想提出建议，或希望与我们合作？告诉我们你正在学习什么，以及你希望如何练习。", updated: "2026年8月24日", chooseTitle: "选择合适的联系方式", cards: [{ label: "产品支持", title: "功能没有正常工作？", body: "请说明发生了什么、你练习的语言，以及使用的设备和浏览器。信息越具体，我们越容易快速定位问题。", email: "support@ailanguagetutor.online" }, { label: "想法与反馈", title: "一起改进 Tutor", body: "告诉我们你想练习的场景、真正有帮助的纠错，或使用过程中让你卡住的地方。", email: "hello@ailanguagetutor.online" }, { label: "合作联系", title: "一起扩大语言学习的可能", body: "我们欢迎语言老师、学习社群，以及关注真实对话练习的团队与我们交流。", email: "partners@ailanguagetutor.online" }], supportTitle: "反馈中最好包含什么", supportLead: "简短、具体的描述能帮助我们更快给出有效回复：", supportBullets: ["学习的语言和使用的练习模式", "出现问题的页面或操作", "你原本期待的结果，以及实际发生的情况", "浏览器、设备和问题发生的大概时间", "如果涉及界面或声音，请附上截图或短视频"], calloutTitle: "每一条消息我们都会认真看。", calloutBody: "产品还在持续成长，目前由团队通过邮件提供支持。我们通常会在两个工作日内回复；如果涉及音频或账号调查，可能需要更长时间。", privacyNote: "想了解我们如何处理信息？请查看", privacyLink: "隐私政策" },
    privacy: { eyebrow: "隐私政策", title: "你的练习记录值得被认真对待", lead: "这份政策说明 AI Language Tutor 可能处理哪些信息、为什么使用这些信息，以及你拥有的选择。", updated: "2026年8月24日", sectionTitles: ["1. 简明说明", "2. 你主动提供的信息", "3. 自动收集的信息", "4. 我们如何使用信息", "5. AI 与服务提供商", "6. 语音与对话数据", "7. 你的选择", "8. 保存期限与安全", "9. 未成年人和跨境使用", "10. 联系方式与政策变更"], sectionTexts: ["我们使用信息来提供对话、纠错、翻译、发音练习、账号功能和产品支持，不出售你的个人信息。", "可能包括姓名、邮箱、登录方式、母语、学习语言、水平、目标、Tutor 偏好、消息、保存的表达，以及你主动使用语音功能时提供的音频。", "我们可能收集浏览器和设备类型、大致地区、访问页面和错误信息，用于保障服务安全、理解使用情况和改进产品。", "用于提供你请求的学习功能，保存设置、词汇、历史和进度，生成更适合你的纠错与练习建议，并处理账号和支持事务。", "我们可能使用认证、语音识别、语言生成、翻译、托管、分析和支付服务商，只共享完成对应服务所需的最少信息。", "当你启用语音功能时，音频会用于转写、对话或发音反馈。请不要在练习中输入高度敏感或他人的私密信息。", "你可以选择文字或语音输入，并在功能支持的范围内删除保存的词汇和历史，或请求修改、导出、删除账号信息。", "我们会在提供服务、履行法律义务、解决争议和维护记录所需的合理期限内保存信息，并采取合理的技术和组织措施保护它。", "本服务不面向13岁以下儿童。服务商可能在你所在国家之外处理信息，我们会根据适用法律采取相应措施。", "隐私问题可发送至 privacy@ailanguagetutor.online。产品、服务商或法律要求发生变化时，我们会更新本政策。"] },
    terms: { eyebrow: "服务条款", title: "一个可以放心练习的地方", lead: "这些条款说明使用 AI Language Tutor 时关于账号、套餐、内容和负责任使用的基本规则。", updated: "2026年8月24日", sectionTitles: ["1. 使用服务", "2. 账号与登录", "3. AI 生成的学习内容", "4. 不当使用", "5. 套餐、付款与试用", "6. 取消与退款", "7. 你的内容与我们的权利", "8. 服务可用性与变更", "9. 暂停与终止", "10. 免责声明与责任限制", "11. 联系我们"], sectionTexts: ["服务包括文字和语音练习、翻译、解释、反馈等语言学习功能。请遵守本条款和适用法律。", "请保持账号信息准确并妥善保管登录凭据。如果发现未经授权的访问，请尽快联系我们。", "Tutor 的回答用于辅助练习，可能存在错误或不适合特定语境的表达，不构成专业、法律、医疗或安全建议。", "不得利用服务违法、骚扰他人、未经授权访问系统、上传恶意软件、擅自复制产品，或规避使用限制与安全措施。", "价格、扣费周期、限制和功能会在价格页与结账页面展示。免费体验也可能有时间、功能或用量限制。", "定期套餐可通过购买时提供的账号或支付控制进行取消。是否退款取决于购买渠道、当地法律和结账时展示的条件。", "你原本拥有的消息、示例和录音权利仍归你所有；你授权我们在提供功能所需范围内托管、处理和展示这些内容。", "产品会持续改进，功能可能调整、暂停或下线，我们不保证每项功能始终在所有设备上可用。", "为了保护用户和服务、处理违规、欠款或法律要求，我们可能限制或暂停账号使用。", "在法律允许的范围内，服务按现状提供，不保证始终不中断、无错误，或适合你的每一个学习目标。", "条款问题请发送至 legal@ailanguagetutor.online，一般产品支持请使用联系我们页面。"] }
  },
  "zh-TW": {
    shell: { back: "返回 AI Language Tutor", updatedLabel: "最後更新", footerBrand: "AI Language Tutor", policyNavigation: "政策導覽", navigation: { contact: "聯絡我們", privacy: "隱私權政策", terms: "服務條款" } },
    contact: { eyebrow: "聯絡我們", title: "一起讓口說練習變得更好", lead: "遇到問題、想提供建議，或希望與我們合作嗎？告訴我們你正在學什麼，以及你想怎麼練習。", updated: "2026年8月24日", chooseTitle: "選擇適合的聯絡方式", cards: [{ label: "產品支援", title: "功能沒有正常運作？", body: "請說明發生了什麼、你正在練習的語言，以及使用的裝置與瀏覽器。資訊越完整，我們越能快速找出原因。", email: "support@ailanguagetutor.online" }, { label: "想法與回饋", title: "一起改進 Tutor", body: "告訴我們你想練習的情境、真正有幫助的訂正，或使用過程中讓你卡住的地方。", email: "hello@ailanguagetutor.online" }, { label: "合作洽談", title: "一起拓展語言學習", body: "我們歡迎語言老師、學習社群，以及重視真實對話練習的團隊與我們交流。", email: "partners@ailanguagetutor.online" }], supportTitle: "回報時最好提供什麼", supportLead: "簡短而具體的說明，能幫助我們更快回覆：", supportBullets: ["正在學習的語言與使用的練習模式", "發生問題的頁面或操作", "原本期待的結果，以及實際發生的情況", "瀏覽器、裝置與問題發生的大概時間", "若涉及畫面或聲音，請附上截圖或短片"], calloutTitle: "每一則訊息我們都會查看。", calloutBody: "目前產品由團隊透過電子郵件提供支援。我們通常會在兩個工作日內回覆；若涉及音訊或帳號調查，可能需要多一點時間。", privacyNote: "想了解我們如何處理資訊？請查看", privacyLink: "隱私權政策" },
    privacy: { eyebrow: "隱私權政策", title: "你的練習記錄值得被好好對待", lead: "本政策說明 AI Language Tutor 可能處理哪些資訊、使用原因，以及你可以做出的選擇。", updated: "2026年8月24日", sectionTitles: ["1. 簡單說明", "2. 你提供的資訊", "3. 自動收集的資訊", "4. 我們如何使用資訊", "5. AI 與服務供應商", "6. 語音與對話資料", "7. 你的選擇", "8. 保存期限與安全", "9. 未成年人與跨境使用", "10. 聯絡方式與政策變更"], sectionTexts: ["我們使用資訊來提供對話、訂正、翻譯、發音練習、帳號功能與產品支援，不會販售你的個人資訊。", "可能包括姓名、電子郵件、登入方式、母語、學習語言、程度、目標、Tutor 偏好、訊息、儲存的表達，以及你啟用語音功能時提供的音訊。", "我們可能收集瀏覽器與裝置類型、大致地區、瀏覽頁面與錯誤資訊，用來維護安全、了解使用情況並改善產品。", "用於提供你要求的學習功能、保存設定與進度、產生更適合你的訂正與練習建議，以及處理帳號和支援事項。", "我們可能使用驗證、語音辨識、語言生成、翻譯、託管、分析與付款服務商，只分享完成服務所需的最少資訊。", "啟用語音功能後，音訊會用於轉寫、對話或發音回饋。請不要在練習中輸入高度敏感或他人的私密資訊。", "你可以選擇文字或語音輸入，也可以在功能允許的範圍內刪除儲存的單字和歷史，或要求修改、匯出、刪除帳號資訊。", "我們會在提供服務、履行法律義務、解決爭議和維護紀錄所需的合理期間保存資訊，並採取合理的安全措施。", "本服務不以13歲以下兒童為對象。服務商可能在你所在國家以外處理資訊，我們會依適用法律採取措施。", "隱私問題請寄至 privacy@ailanguagetutor.online。產品、服務商或法律要求變更時，我們會更新本政策。"] },
    terms: { eyebrow: "服務條款", title: "一個可以安心練習的地方", lead: "這些條款說明使用 AI Language Tutor 時，關於帳號、方案、內容和負責任使用的基本規則。", updated: "2026年8月24日", sectionTitles: ["1. 使用服務", "2. 帳號與登入", "3. AI 產生的學習內容", "4. 不當使用", "5. 方案、付款與試用", "6. 取消與退款", "7. 你的內容與我們的權利", "8. 服務可用性與變更", "9. 暫停與終止", "10. 免責聲明與責任限制", "11. 聯絡我們"], sectionTexts: ["服務包含文字與語音練習、翻譯、解釋和回饋等語言學習功能。請遵守本條款與適用法律。", "請保持帳號資訊正確並妥善保管登入憑證。若發現未經授權的存取，請盡快聯絡我們。", "Tutor 的回答是練習輔助，可能有錯誤或不適合特定情境的表達，不構成專業、法律、醫療或安全建議。", "不得利用服務違法、騷擾他人、未經授權存取系統、上傳惡意軟體、擅自複製產品，或規避使用限制與安全措施。", "價格、扣款週期、限制和功能會在價格頁與結帳頁面顯示。免費體驗也可能有時間、功能或用量限制。", "定期方案可透過購買時提供的帳號或付款控制取消。退款依購買管道、當地法律及結帳時的條件決定。", "你原本擁有的訊息、範例和錄音權利仍歸你所有；你授權我們在提供功能所需範圍內託管、處理和展示內容。", "產品會持續改進，功能可能調整、暫停或下線，我們不保證每項功能始終在所有裝置上可用。", "為保護使用者與服務、處理違規、欠款或法律要求，我們可能限制或暫停帳號使用。", "在法律允許的範圍內，服務按現況提供，不保證始終不中斷、無錯誤，或適合每一個學習目標。", "條款問題請寄至 legal@ailanguagetutor.online，一般產品支援請使用聯絡我們頁面。"] }
  },
  ko: {
    shell: { back: "AI Language Tutor로 돌아가기", updatedLabel: "최종 업데이트", footerBrand: "AI Language Tutor", policyNavigation: "정책 안내", navigation: { contact: "문의", privacy: "개인정보 보호", terms: "이용약관" } },
    contact: { eyebrow: "문의", title: "말하기 연습을 더 나아지게 만들어요.", lead: "사용 중 도움이 필요하거나 의견이 있나요? 무엇을 배우고 있는지 함께 알려 주세요.", updated: "2026년 8월 24일", chooseTitle: "문의 목적에 맞는 방법을 선택하세요", cards: [{ label: "제품 지원", title: "무언가 제대로 작동하지 않나요?", body: "어떤 일이 있었는지, 어떤 언어를 연습했는지, 어떤 기기와 브라우저를 사용했는지 알려 주시면 더 빠르게 확인할 수 있습니다.", email: "support@ailanguagetutor.online" }, { label: "아이디어와 의견", title: "Tutor를 함께 만들어 주세요", body: "연습하고 싶은 대화, 도움이 된 교정, 사용 중 막혔던 지점을 알려 주세요.", email: "hello@ailanguagetutor.online" }, { label: "파트너십", title: "함께 학습 경험을 넓혀요", body: "언어 교사, 학습 커뮤니티, 대화 중심 학습을 만드는 팀과의 협업을 기다립니다.", email: "partners@ailanguagetutor.online" }], supportTitle: "지원 요청에 포함하면 좋은 내용", supportLead: "짧고 구체적으로 적어 주시면 더 빠르게 도와드릴 수 있어요.", supportBullets: ["배우던 언어와 사용한 연습 모드", "문제가 발생한 페이지나 동작", "기대했던 결과와 실제 결과", "브라우저, 기기, 문제가 발생한 대략적인 시간", "화면이나 음성 문제라면 스크린샷 또는 짧은 녹화"], calloutTitle: "모든 메시지를 확인합니다.", calloutBody: "현재 지원은 이메일로 운영하고 있으며 보통 영업일 기준 2일 안에 답변드리려고 합니다. 음성이나 계정 문제는 확인에 더 시간이 걸릴 수 있습니다.", privacyNote: "정보 처리 방법은", privacyLink: "개인정보 보호정책" },
    privacy: { eyebrow: "개인정보 보호", title: "당신의 연습은 개인적인 기록입니다.", lead: "AI Language Tutor가 어떤 정보를 다루고 왜 사용하는지, 어떤 선택을 할 수 있는지 안내합니다.", updated: "2026년 8월 24일", sectionTitles: ["1. 한눈에 보기", "2. 제공하는 정보", "3. 자동으로 수집되는 정보", "4. 정보 이용 방법", "5. AI와 서비스 제공업체", "6. 음성 및 대화 데이터", "7. 선택할 수 있는 사항", "8. 보관 기간과 보안", "9. 아동 및 해외 이용", "10. 문의와 정책 변경"], sectionTexts: ["대화, 교정, 번역, 발음 연습, 계정 이용, 고객 지원을 제공하기 위해 정보를 사용합니다. 개인정보를 판매하지 않습니다.", "이름, 이메일, 로그인 제공업체, 모국어와 학습 언어, 레벨, 목표, Tutor 설정, 메시지, 저장한 표현, 음성 입력 등이 포함될 수 있습니다.", "브라우저와 기기 유형, 대략적인 지역, 방문한 페이지, 오류 정보 등 서비스 보안과 개선에 필요한 기술 정보를 받을 수 있습니다.", "요청한 학습 기능을 제공하고 설정과 기록을 저장하며, 개인화된 교정과 연습 제안을 제공하고 서비스 안전성을 유지하는 데 사용합니다.", "인증, 음성 인식, 언어 생성, 번역, 호스팅, 분석, 결제 전문업체를 사용할 수 있으며 필요한 최소한의 정보만 공유합니다.", "음성 기능을 켜면 음성은 전사, 대화, 발음 피드백을 위해 처리됩니다. 연습 대화에는 민감한 정보를 입력하지 마세요.", "텍스트와 음성 중 원하는 방식을 선택하고, 가능한 범위에서 저장한 단어와 기록을 삭제하거나 계정 정보의 수정·삭제를 요청할 수 있습니다.", "서비스 제공과 법적 의무에 필요한 기간 동안 정보를 보관합니다. 합리적인 보호 조치를 사용하지만 온라인 서비스의 완전한 보안을 보장할 수는 없습니다.", "본 서비스는 만 13세 미만 아동을 대상으로 하지 않습니다. 제공업체가 다른 국가에서 정보를 처리할 수 있으며 관련 법을 고려합니다.", "개인정보 문의는 privacy@ailanguagetutor.online으로 보내 주세요. 제품, 제공업체 또는 법률이 변경되면 정책을 업데이트할 수 있습니다."] },
    terms: { eyebrow: "이용약관", title: "편안하게 연습할 수 있는 공간", lead: "AI Language Tutor의 계정, 요금제, 콘텐츠, 책임 있는 이용에 관한 기본 규칙입니다.", updated: "2026년 8월 24일", sectionTitles: ["1. 서비스 이용", "2. 계정과 로그인", "3. AI 학습 콘텐츠", "4. 허용되지 않는 이용", "5. 요금제·결제·체험", "6. 취소와 환불", "7. 콘텐츠와 권리", "8. 서비스 변경과 이용 가능성", "9. 이용 제한과 종료", "10. 면책과 책임 제한", "11. 문의"], sectionTexts: ["텍스트와 음성 언어 연습, 번역, 설명, 피드백 기능을 제공합니다. 본 약관과 관련 법률에 따라 이용해 주세요.", "계정 정보를 정확하게 유지하고 로그인 정보를 안전하게 관리해 주세요. 무단 접근을 알게 되면 신속히 알려 주세요.", "Tutor의 답변은 연습을 위한 제안이며 오류나 상황에 맞지 않는 표현이 있을 수 있습니다. 전문적·법률·의료·안전 조언을 대신하지 않습니다.", "법 위반, 타인 괴롭힘, 무단 접근, 악성코드 업로드, 무단 복제, 사용량 제한이나 보안 조치 우회는 금지됩니다.", "가격, 결제 주기, 제한, 포함 기능은 Pricing 페이지와 결제 화면에 표시됩니다. 무료 이용에도 시간이나 기능 제한이 있을 수 있습니다.", "반복 결제 플랜은 구매 시 안내된 방법으로 취소할 수 있습니다. 환불은 구매 채널과 지역 법률, 결제 조건에 따라 달라집니다.", "제출한 메시지와 녹음에 대한 기존 권리는 유지됩니다. 기능 제공에 필요한 범위에서 처리할 수 있는 권한을 부여합니다.", "제품 개선에 따라 기능은 변경·일시 중단·종료될 수 있으며 모든 기능이 항상 모든 기기에서 제공된다고 보장하지 않습니다.", "사용자와 서비스 보호, 약관 위반, 미납, 법률 준수를 위해 이용을 제한하거나 중지할 수 있습니다.", "법이 허용하는 범위에서 서비스는 현재 상태로 제공되며 AI 답변이 항상 중단 없이 정확하거나 목표에 적합하다고 보장하지 않습니다.", "약관 문의는 legal@ailanguagetutor.online으로, 일반적인 도움은 문의 페이지로 보내 주세요."] }
  },
  es: {
    shell: { back: "Volver a AI Language Tutor", updatedLabel: "Última actualización", footerBrand: "AI Language Tutor", policyNavigation: "Políticas", navigation: { contact: "Contacto", privacy: "Privacidad", terms: "Términos" } },
    contact: { eyebrow: "CONTACTO", title: "Hagamos mejor la práctica oral.", lead: "¿Necesitas ayuda, tienes una idea o quieres colaborar? Cuéntanos qué estás aprendiendo y cómo te gustaría practicarlo.", updated: "24 de agosto de 2026", chooseTitle: "Elige el motivo de tu mensaje", cards: [{ label: "Soporte del producto", title: "¿Algo no funciona?", body: "Cuéntanos qué ocurrió, qué idioma practicabas y qué dispositivo o navegador estabas usando. Con esos datos podemos investigar más rápido.", email: "support@ailanguagetutor.online" }, { label: "Ideas y comentarios", title: "Ayuda a mejorar el Tutor", body: "Comparte las conversaciones que quieres practicar, las correcciones que te sirven o los momentos en que la experiencia se vuelve confusa.", email: "hello@ailanguagetutor.online" }, { label: "Colaboraciones", title: "Construyamos juntos", body: "Nos interesa hablar con profesores de idiomas, comunidades de aprendizaje y equipos que crean experiencias basadas en conversaciones reales.", email: "partners@ailanguagetutor.online" }], supportTitle: "Qué incluir en un mensaje de soporte", supportLead: "Un mensaje breve y concreto nos ayuda a darte una respuesta útil antes:", supportBullets: ["El idioma que aprendías y el modo de práctica utilizado", "La página o acción donde apareció el problema", "Qué esperabas que ocurriera y qué ocurrió en realidad", "Tu navegador, dispositivo y hora aproximada del problema", "Una captura o grabación breve si el problema es visual o de audio"], calloutTitle: "Leemos todos los mensajes.", calloutBody: "Mientras el producto crece, atendemos el soporte por correo electrónico. Intentamos responder en un plazo de dos días laborables, aunque los casos de audio o cuenta pueden requerir más tiempo.", privacyNote: "¿Quieres saber cómo tratamos la información? Consulta nuestra", privacyLink: "Política de privacidad" },
    privacy: { eyebrow: "PRIVACIDAD", title: "Tu práctica merece cuidado.", lead: "Esta política explica qué información puede tratar AI Language Tutor, para qué la usamos y qué opciones tienes.", updated: "24 de agosto de 2026", sectionTitles: ["1. Resumen", "2. Información que proporcionas", "3. Información que recopilamos automáticamente", "4. Cómo usamos la información", "5. IA y proveedores de servicios", "6. Datos de voz y conversaciones", "7. Tus opciones", "8. Conservación y seguridad", "9. Menores y uso internacional", "10. Contacto y cambios"], sectionTexts: ["Usamos información para ofrecer conversaciones, correcciones, traducciones, práctica de pronunciación, acceso a la cuenta y soporte. No vendemos tus datos personales.", "Puede incluir tu nombre, correo, método de inicio de sesión, idioma nativo, idioma de aprendizaje, nivel, objetivos, preferencias, mensajes, frases guardadas y audio cuando activas funciones de voz.", "Podemos recibir datos técnicos básicos como navegador, tipo de dispositivo, región aproximada, páginas visitadas y errores para proteger y mejorar el servicio.", "La usamos para ofrecer las funciones que solicitas, recordar ajustes e historial, personalizar correcciones y sugerencias, y gestionar asuntos de cuenta y soporte.", "Podemos apoyarnos en proveedores de autenticación, reconocimiento de voz, generación de lenguaje, traducción, alojamiento, análisis y pagos. Compartimos solo lo necesario.", "El audio se procesa para transcripción, conversación o comentarios de pronunciación cuando activas esas funciones. No compartas información sensible en una práctica.", "Puedes elegir texto o voz y, cuando esté disponible, eliminar palabras guardadas e historial o pedir que corrijamos, exportemos o eliminemos datos de tu cuenta.", "Conservamos la información durante el tiempo razonablemente necesario para prestar el servicio, cumplir obligaciones legales y resolver incidencias, aplicando medidas de seguridad razonables.", "El servicio no está dirigido a menores de 13 años. Algunos proveedores pueden tratar información fuera de tu país conforme a la legislación aplicable.", "Para consultas de privacidad, escribe a privacy@ailanguagetutor.online. Actualizaremos esta política cuando cambien el producto, los proveedores o las obligaciones legales."] },
    terms: { eyebrow: "TÉRMINOS", title: "Un lugar claro para practicar.", lead: "Estos términos explican las reglas básicas de AI Language Tutor sobre cuentas, planes, contenido y uso responsable.", updated: "24 de agosto de 2026", sectionTitles: ["1. Uso del servicio", "2. Cuenta e inicio de sesión", "3. Contenido de aprendizaje generado por IA", "4. Uso no permitido", "5. Planes, pagos y pruebas", "6. Cancelaciones y reembolsos", "7. Tu contenido y nuestros derechos", "8. Disponibilidad y cambios", "9. Suspensión y terminación", "10. Exenciones y límites", "11. Contacto"], sectionTexts: ["El servicio ofrece práctica de idiomas por texto y voz, traducciones, explicaciones y comentarios. Debes usarlo de acuerdo con estos términos y la ley aplicable.", "Mantén actualizados los datos de tu cuenta y protege tus credenciales. Avísanos cuanto antes si detectas un acceso no autorizado.", "Las respuestas del Tutor sirven para practicar y pueden contener errores o expresiones poco adecuadas para un contexto. No sustituyen consejos profesionales, legales, médicos o de seguridad.", "No puedes usar el servicio para infringir la ley, acosar, acceder sin autorización, subir malware, copiar el producto o eludir límites y medidas de seguridad.", "Los precios, ciclos de cobro, límites y funciones aparecen en la página de precios y en el pago. La experiencia gratuita también puede tener límites.", "Puedes cancelar un plan recurrente mediante los controles disponibles al comprar. Los reembolsos dependen del canal de compra, la ley local y las condiciones del pago.", "Conservas los derechos que ya tenías sobre tus mensajes, ejemplos y grabaciones. Nos autorizas a procesarlos en la medida necesaria para prestar las funciones.", "El producto se mejora continuamente y algunas funciones pueden cambiar, pausarse o retirarse. No garantizamos que todo esté disponible en cada dispositivo y momento.", "Podemos limitar o suspender el acceso para proteger a los usuarios y el servicio, investigar abusos, gestionar impagos o cumplir la ley.", "En la medida permitida por la ley, el servicio se ofrece tal cual y no garantizamos que sea ininterrumpido, libre de errores o adecuado para todos los objetivos.", "Para preguntas sobre estos términos, escribe a legal@ailanguagetutor.online. Para ayuda general, usa la página de contacto."] }
  }
};

const publicContactEmail = "scottthornton815@gmail.com";

function replaceContactEmails(copy: InfoCopy): InfoCopy {
  const replace = (value: string) => value.replace(/(?:support|hello|partners|privacy|legal)@ailanguagetutor\.online/g, publicContactEmail);
  return {
    ...copy,
    contact: {
      ...copy.contact,
      cards: copy.contact.cards.map((card) => ({ ...card, email: publicContactEmail }))
    },
    privacy: {
      ...copy.privacy,
      sections: copy.privacy.sections.map((section) => ({
        ...section,
        paragraphs: section.paragraphs?.map(replace),
        bullets: section.bullets?.map(replace)
      }))
    },
    terms: {
      ...copy.terms,
      sections: copy.terms.sections.map((section) => ({
        ...section,
        paragraphs: section.paragraphs?.map(replace),
        bullets: section.bullets?.map(replace)
      }))
    }
  };
}

export function getInfoCopy(locale: Locale): InfoCopy {
  if (locale === "en") return replaceContactEmails(english);
  const copy = localized[locale];
  return replaceContactEmails({
    locale,
    shell: copy.shell,
    contact: copy.contact,
    privacy: { ...copy.privacy, sections: textSections(copy.privacy.sectionTitles, copy.privacy.sectionTexts) },
    terms: { ...copy.terms, sections: textSections(copy.terms.sectionTitles, copy.terms.sectionTexts) }
  });
}
